#!/bin/bash

curl -sS -H "Content-Type: application/json" \
    -X PUT "localhost:5000/tests/TESTE1" -d "{
        \"id\": \"TESTE1\",
        \"questions\": [\"UKEINSBD0151\", \"UKEINSBD0152\", \"UKEINSBD0150\"],
        \"config\": {
            \"description\": \"Este teste foi gerado de forma automatica\",
            \"test_type\": \"Avaliacao\",
            \"number_questions\": 2,
            \"maximum_displayed_answers\": 2,
            \"avg_difficulty\": 100,
            \"total_time\": 100,
            \"question_types\": [\"tipo\", \"\"],
            \"language\": \"uk\",
            \"domain\": \"BD\",
            \"subdomains\": [\"\"],
            \"subsubdomains\": [\"subdominio_adicionado_no_teste\"],
            \"inserted_by\": \"Belo, O\",
            \"date\": [\"2021-04-10\", \"2021-04-12\"],
            \"obs\": \"Update Test test\",
            \"visibility\": \"author\"
        }
    }"
