#!/bin/bash

curl -sS -H "Content-Type: application/json" \
    -X POST "localhost:5000/generator/edit" -d "{
       \"replace\": [
           1
       ],
       \"test\": {
            \"id\": \"generated_test\",
            \"config\": {
                \"description\": \"Este teste foi gerado de forma automatica\",
                \"test_type\": \"Avaliação\",
                \"number_questions\": 2,
                \"maximum_displayed_answers\": 2,
                \"avg_difficulty\": 2,
                \"total_time\": 120,
                \"question_types\": [\"\"],
                \"language\": \"uk\",
                \"domain\": {
                    \"study_cycle\": \"University Course\",
                    \"scholarity\": \"Informatics Engineering\",
                    \"description\": \"Database Systems\"
                }, 
                \"subdomains\": [\"SQL\", \"SQL2\"],
                \"subsubdomains\": [\"\"],
                \"inserted_by\": \"Belo, O\",
                \"date\": [\"2021-04-10\", \"2021-04-11\"],
                \"obs\": \"Test request for generating a test\",
                \"visibility\": \"author\"  
            }, 
            \"questions\": [
                {
                    \"answering_time\": \"60\", 
                    \"body\": [
                        {
                            \"answer\": \"True.\", 
                            \"correction\": 1, 
                            \"mandatory\": true
                        }, 
                        {
                            \"answer\": \"False.\", 
                            \"correction\": 0, 
                            \"mandatory\": true
                        }
                    ], 
                    \"difficulty_level\": \"1\", 
                    \"display_mode\": \"G\", 
                    \"domain\": {
                        \"description\": \"Database Systems\", 
                        \"scholarity\": \"Informatics Engineering\", 
                        \"study_cycle\": \"University Course\"
                    }, 
                    \"header\": \"SQL is a language used for programming and designed specifically for data description, manipulation, and control in a relational database system. This statement is:\", 
                    \"id\": \"UKEINSBD0150\", 
                    \"images\": \"\", 
                    \"inserted_at\": \"2019-09-12\", 
                    \"inserted_by\": \"Belo, O\", 
                    \"language\": \"uk\", 
                    \"notes\": \"Para utiliza\u00e7\u00e3o exclusiva da plataforma educacional Leonardo\", 
                    \"precedence\": [], 
                    \"repetitions\": \"0\", 
                    \"solution\": \"\", 
                    \"source\": \"Belo, O., Cadernos de Problemas - Sistemas de Bases de Dados, Departamento de Inform\u00e1tica, Escola de Engenharia, Universidade do Minho, 2019\", 
                    \"status\": \"E\", 
                    \"subdomain\": \"SQL\", 
                    \"subsubdomain\": \"\", 
                    \"type\": \"\", 
                    \"validated_at\": \"\", 
                    \"validated_by\": \"\", 
                    \"videos\": \"\"
                }, 
                {
                    \"answering_time\": \"60\", 
                    \"body\": [
                        {
                            \"answer\": \"True.\", 
                            \"correction\": 1, 
                            \"mandatory\": true
                        }, 
                        {
                            \"answer\": \"False.\", 
                            \"correction\": 0, 
                            \"mandatory\": true
                        }
                    ], 
                    \"difficulty_level\": \"1\", 
                    \"display_mode\": \"G\", 
                    \"domain\": {
                        \"description\": \"Database Systems\", 
                        \"scholarity\": \"Informatics Engineering\", 
                        \"study_cycle\": \"University Course\"
                    }, 
                    \"header\": \"SQL is a language used for programming and designed specifically for data description, manipulation, and control in a relational database system. This statement is:\", 
                    \"id\": \"UKEINSBD0153\", 
                    \"images\": \"\", 
                    \"inserted_at\": \"2019-09-12\", 
                    \"inserted_by\": \"Belo, O\", 
                    \"language\": \"uk\", 
                    \"notes\": \"Para utiliza\u00e7\u00e3o exclusiva da plataforma educacional Leonardo\", 
                    \"precedence\": [], 
                    \"repetitions\": \"0\", 
                    \"solution\": \"\", 
                    \"source\": \"Belo, O., Cadernos de Problemas - Sistemas de Bases de Dados, Departamento de Inform\u00e1tica, Escola de Engenharia, Universidade do Minho, 2019\", 
                    \"status\": \"E\", 
                    \"subdomain\": \"SQL\", 
                    \"subsubdomain\": \"\", 
                    \"type\": \"\", 
                    \"validated_at\": \"\", 
                    \"validated_by\": \"\", 
                    \"videos\": \"\"
                }
            ]
       }
    }"

